apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxmotoweb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maxmotoweb
  template:
    metadata:
      labels:
        app: maxmotoweb
    spec:
      containers:
      - name: maxmotoweb
        image: shantanugadekardocker/maxmoto:1.0.4
        ports:
        - containerPort: 80
